--- # Poggit-CI Manifest
build-by-default: true
branches:
- stable
projects:
  KnockbackFFA:
    path: ""
    libs:
      - src: "CortexPE/Commando/Commando"
        version: "^3.0.0"
      - src: "jojoe77777/FormAPI/libFormAPI"
        version: "^2.0.0"
...
